version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 373793355777.dkr.ecr.ap-southeast-1.amazonaws.com
      - IMAGE_NAME=englishtest24-backend
      - REPOSITORY_URI=373793355777.dkr.ecr.ap-southeast-1.amazonaws.com/englishtest24-backend
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME:latest .
      - docker tag $IMAGE_NAME:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"englishtest24-backend","imageUri":"%s"}]' $REPOSITORY_URI:latest > nestjs.json
artifacts:
  files: nestjs.json