server:
  port: 3000
  url: 'http://localhost:3000'

client:
  port: 80
  url: 'http://localhost:80'

db:
  host: 'englishtest24-db.cp9armlyndkz.ap-southeast-1.rds.amazonaws.com'
  username: 'root'
  password: 'blueOcean2809'
  synchronize: false