server:
  port: 3000
  url: 'http://localhost:3000'

client:
  port: 8080
  url: 'http://localhost:8080'

db:
  host: 'englishtest24db.cp9armlyndkz.ap-southeast-1.rds.amazonaws.com'
  username: 'root'
  password: 'blueOcean2809'
  synchronize: false