server:
  port: 3000
  url: 'https://ns1.englishtest24.tk'

client:
  port: 80
  url: 'https://www.englishtest24.tk'

db:
  host: 'englishtest24db.cp9armlyndkz.ap-southeast-1.rds.amazonaws.com'
  username: 'root'
  password: 'blueOcean2809'
  synchronize: false